### ISSUE TITLE
add QSpecificFuelCons

### ISSUE THREAD

**Issue by Redmonkeycloud** [e3modelling/OPEN-PROM#15]
QSpecificFuelCons(allCy,TRANSE,TTECH,TEA,EF,YTIME)  ==  "Compute Specific Fuel Consumption"

- [x] `VSpecificFuelCons` == "Specific Fuel Consumption ()"
- [x] `iInitSpecFuelCons` == "Initial Specific fuel consumption ()"
- [x] `VFuelPriceSub` == "Fuel prices per subsector and fuel (k$2015/toe)"
- [x] `iFuelPrice`
- [x] `iElastA` == "Activity Elasticities per subsector (1)"
- [x] `iFPDL` == "Polynomial Distribution Lags (PDL) Coefficients per subsector (1)"

**Comment by giannou** [comment]
a mrprom:::calcIInitSpecFuelCons function is needed, for 2017, from ENERDATA and IRF
