### ISSUE TITLE
Shouldn't at this point all FIXME in the code be issues?

### ISSUE THREAD

**Issue by giannou** [e3modelling/OPEN-PROM#18]
Also, what happens when a new PR is merged? Will we get duplicated issues from the parsing of all FIXME comments in the code that have already been converted to issues at the last PR?

**Comment by derevirn** [comment]
`Shouldn't at this point all FIXME in the code be issues?`

All correctly formatted comments have been successfully added as issues, and I closed most of them to reduce clutter. In case you are wondering about the end of line `!! FIXME`, please refer to our chat last Friday.

`Will we get duplicated issues from the parsing of all FIXME comments in the code that have already been converted to issues at the last PR?`

Thankfully, the comment parsing software is "smart" enough to avoid creating duplicate issues, so this shouldn't be a problem!

**Comment by giannou** [comment]
Perfect, thanks!
