### ISSUE TITLE
log file option ("lo") is disabled with addition of DevMode option

### ISSUE THREAD

**Issue by giannou** [e3modelling/OPEN-PROM#94]
https://github.com/e3modelling/OPEN-PROM/blob/6d130b86279d0980a629ca7e2ce2c801b3b17fd9/.vscode/tasks.json#L9

it seems to me that adding the `DevMode` command line parameter disables the functionality of `--lo=2` ("write log to file"); log output is printed on the screen instead of a file, maybe reversing the order of the parameters fixes this?

**Comment by derevirn** [comment]
@giannou I'll check this out.

**Comment by derevirn** [comment]
@giannou 
I figured out an alternative command that works and has the same effect (std output & writing to log file). I can include it in my next PR, or make the change yourself if preferable.

`gams main.gms --DevMode=1 -logOption 4`

**Comment by giannou** [comment]
go ahead and add it in your next PR, thanks!

**Comment by giannou** [comment]
fixed with cdebd945a6bff549986e1ff27aacd924ac2d9ccb
